root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "react"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
rules:
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - argsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  "@typescript-eslint/strict-boolean-expressions": "warn"
  semi: ["error", "always"]
